name: Firmware verification

on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, docker]
    container:
      image: ghcr.io/sakuglumoff/iida-devkit:trunk
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build firmware
        run: |
          rm -rf /__w/iida-devkit/iida-devkit/.west /__w/iida-devkit/iida-devkit/*
          export PATH=$PATH:/github/home/.local/bin
          pip install west
          west init \
            -m "${{ github.event.pull_request.head.repo.clone_url || format('{0}/{1}.git', github.server_url, github.repository) }}" \
            --mr "${{ github.head_ref || github.ref_name }}"
          west update
          pip install -r zephyr/scripts/requirements.txt
          west zephyr-export
          west build -b iida_devkit application/app
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: |
            build/zephyr/zephyr.hex
          if-no-files-found: error

