name: FW Verification
on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:
jobs:
  Codecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Build docker image
        # Build the docker image with current user's IDs so that permissions to the workspace are retained.
        run: docker build -t iida-devkit .devcontainer --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
      - name: Codecheck
        run: |
          docker run -v $PWD:/iida-devkit -w /iida-devkit iida-devkit \
          ./firmware/scripts/codechecker.sh
      - name: Build
        run: |
          docker run -v $PWD:/iida-devkit -w /iida-devkit iida-devkit \
          /bin/bash -c "\
            cmake -G Ninja -S ./firmware -B ./firmware/build -DCMAKE_TOOLCHAIN_FILE=cmake/arm-none-eabi.cmake -DCMAKE_BUILD_TYPE=Debug && \
            cmake --build ./firmware/build \
          "
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: |
            ./firmware/build/bootloader/bootloader.hex
            ./firmware/build/application/application.hex
          if-no-files-found: error
